# Generated by Django 4.2.10 on 2024-08-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_available_course_price_group_course_and_more'),
        ('users', '0004_remove_subscription_group_useringroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInGroup',
            new_name='StudentInGroup',
        ),
    ]
