# Generated by Django 4.2.10 on 2024-08-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_available_course_price_group_course_and_more'),
        ('users', '0005_rename_useringroup_studentingroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'course')},
        ),
    ]
