# Generated by Django 4.2.10 on 2024-08-20 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_tltle_group_title'),
        ('users', '0006_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentingroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_in_group', to='courses.group'),
        ),
        migrations.AlterField(
            model_name='studentingroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
