# Generated by Django 4.2.10 on 2024-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_group_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tltle',
            new_name='title',
        ),
    ]
