# Generated by Django 4.2.10 on 2024-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_tltle_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
